// Media coverage & mentions — curated from press archive (outlet, headline, date, link only).
// kind: press | agency | industry | podcast | webinar | recognition
// marquee: true floats the item into the featured band.
window.MEDIA = [
 {outlet:"The New York Times", title:"How Your Car Might Be Making Roads Safer", date:"Dec 20, 2024", year:2024, kind:"press", marquee:true,
  note:"Front page of the Dec 21, 2024 print edition — features the Purdue connected-vehicle research group.",
  url:"https://www.nytimes.com/2024/12/20/technology/connected-cars-roads-data.html"},
 {outlet:"FHWA Innovator", title:"Crowdsourced Data Improves Safety on Indiana Roads", date:"Nov/Dec 2021", year:2021, kind:"agency", marquee:true,
  note:"U.S. DOT Federal Highway Administration innovation newsletter, Issue 87.",
  url:"https://www.fhwa.dot.gov/innovation/innovator/issue87/page_01.html"},
 {outlet:"Google Cloud", title:"Purdue University JTRP Customer Story: Traffic Insights from Connected Vehicles", date:"2023", year:2023, kind:"industry", marquee:true,
  note:"Case study on the JTRP big-data pipeline built on Google Cloud.",
  url:"https://cloud.google.com/customers/purduejtrp"},
 {outlet:"U.S. DOT ITS JPO", title:"Place Queue Trucks Ahead of a Work Zone to Reduce Hard Braking and Crash Risks", date:"Jun 28, 2021", year:2021, kind:"agency", marquee:true,
  note:"ITS Deployment Evaluation — Lessons Learned, drawn from the Indiana queue-truck study.",
  url:"https://www.itskrs.its.dot.gov/node/209929"},
 {outlet:"Purdue University News", title:"Connected vehicles: the latest tool to give engineers real-time insight into highway traffic congestion issues", date:"Mar 22, 2023", year:2023, kind:"press",
  url:"https://purdue.edu/newsroom/releases/2023/Q1/connected-vehicles-the-latest-tool-to-give-engineers-real-time-insight-into-highway-traffic-congestion-issues.html"},
 {outlet:"The Times of India", title:"Explained: How connected vehicle data can help track and predict traffic congestion during storms", date:"2023", year:2023, kind:"press",
  url:"https://timesofindia.indiatimes.com/videos/international/explained-how-connected-vehicle-data-can-help-track-and-predicttraffic-congestion-during-storms/videoshow/99244161.cms"},
 {outlet:"Route Fifty", title:"How data from connected cars can improve traffic safety", date:"Feb 15, 2023", year:2023, kind:"press",
  url:"https://www.route-fifty.com/digital-government/2023/02/how-data-connected-cars-can-improve-traffic-safety/382988/"},
 {outlet:"Fox59 Indianapolis", title:"Hundreds of thousands of eclipse visitors expected to create traffic headache", date:"Apr 2024", year:2024, kind:"press",
  note:"Coverage ahead of the 2024 total solar eclipse, informed by JTRP mobility analysis.",
  url:"https://fox59.com/news/hundreds-of-thousands-eclipse-visitors-expected-to-create-traffic-headache/"},
 {outlet:"Datanami", title:"Big Data Via Connected Cars Hits the Open Road", date:"Apr 8, 2021", year:2021, kind:"press",
  url:"https://www.datanami.com/2021/04/08/big-data-via-connected-cars-hits-the-open-road/"},
 {outlet:"For Construction Pros", title:"Connecting the DOTs: How Data Improves Work Zone Safety", date:"Oct 4, 2021", year:2021, kind:"industry",
  url:"https://www.forconstructionpros.com/asphalt/article/21590993/connecting-the-dots-how-data-improves-work-zone-safety"},
 {outlet:"Field Technologies Online", title:"How Snow Removal Operations Benefit From Telematics And The IoT", date:"Dec 28, 2021", year:2021, kind:"industry",
  url:"https://www.fieldtechnologiesonline.com/doc/how-snow-removal-operations-benefit-from-telematics-and-the-iot-0001"},
 {outlet:"Informed Infrastructure", title:"Connected Vehicles the Latest Tool To Give Engineers Real-Time Insight Into Highway Traffic Congestion Issues", date:"Mar 23, 2023", year:2023, kind:"industry",
  url:"https://informedinfrastructure.com/80906/connected-vehicles-the-latest-tool-to-give-engineers-real-time-insight-into-highway-traffic-congestion-issues/"},
 {outlet:"ITS International (UK)", title:"Compass IoT CV data puts heat on UK motorways", date:"2024", year:2024, kind:"press",
  note:"Purdue collaboration generating speed heatmaps for UK motorways from connected-vehicle data.",
  url:"https://www.itsinternational.com/news/compass-iot-cv-data-puts-heat-uk-motorways"},
 {outlet:"LCRIG (UK)", title:"Compass partners with Purdue University to generate speed heatmaps for UK motorways using connected vehicle data", date:"Feb 19, 2025", year:2025, kind:"industry",
  url:"https://lcrig.org.uk/2025/02/19/compass-partners-with-purdue-university-to-generate-speed-heatmaps-for-uk-motorways-using-connected-vehicle-data/"},
 {outlet:"Compass IoT (UK)", title:"Exclusive Webinar: UK Motorway Analysis from Purdue University", date:"2025", year:2025, kind:"webinar", url:null},
 {outlet:"Vizzion", title:"NCDOT, Vizzion, and Iteris Join Forces to Improve Driver Safety and Traffic Flow with On-Vehicle Camera Data", date:"Jan 27, 2025", year:2025, kind:"webinar",
  url:"https://vizzion.com/Iteris-NCDOT.html"},
 {outlet:"Mass Transit", title:"Infrastructure Technology Podcast discusses advancements in transportation infrastructure", date:"2025", year:2025, kind:"podcast",
  url:"https://www.masstransitmag.com/technology/article/55263720/infrastructure-technology-podcast-discusses-advancements-in-transportation-infrastructure"},
 {outlet:"Compass IoT — Byte Size", title:"Byte Size podcast: connected-vehicle data in practice", date:"2024", year:2024, kind:"podcast", url:null},
 {outlet:"HAAS Alert", title:"A Conversation with Professor Darcy Bullock", date:"Dec 10, 2024", year:2024, kind:"industry",
  note:"Digital-alerting Q&A featuring the Purdue queue-truck and work-zone research.",
  url:"https://www.haasalert.com/blog/digital-alerting-conversation-darcy-bullock"},
 {outlet:"Wejo", title:"Purdue University and Indiana DOT Use Connected Vehicle Data to Improve Work Zone Safety", date:"2021", year:2021, kind:"industry", note:"Wejo has since closed; the original page is offline.", url:null},
 {outlet:"Wejo", title:"Purdue University uses Wejo Data to Improve Mobility Understanding", date:"Nov 23, 2020", year:2020, kind:"industry", note:"Wejo has since closed; the original page is offline.", url:null},
 {outlet:"Wejo", title:"National Work Zone Awareness Week 2021 Panel with Purdue University, Google, and the Indiana DOT", date:"Apr 22, 2021", year:2021, kind:"webinar", note:"Wejo has since closed; the original page is offline.", url:null},
 {outlet:"Purdue Engineering Review (Medium)", title:"Putting data in the driver's seat", date:"2021", year:2021, kind:"press",
  url:"https://medium.com/purdue-engineering/putting-data-in-the-drivers-seat-e06122696fc8"},
 {outlet:"Purdue Engineering Review (Medium)", title:"What Your Car Knows Can Make the Roads Safer — and Pave the Way for Connected and Autonomous Vehicles", date:"2019", year:2019, kind:"press",
  url:"https://medium.com/purdue-engineering/what-your-car-knows-can-make-the-roads-safer-and-pave-the-way-for-connected-and-autonomous-430f679d5f63"},
 {outlet:"Google Cloud", title:"Purdue University: Making electric vehicle investments more equitable", date:"Apr 7, 2023", year:2023, kind:"industry", url:null},
 {outlet:"Google Cloud", title:"Research Innovators — 2024 Cohort", date:"2024", year:2024, kind:"recognition",
  note:"Selected to the fourth global cohort of Google Cloud Research Innovators.",
  url:"https://cloud.google.com/blog/topics/public-sector/google-cloud-research-innovators-launch-fourth-cohort-to-drive-innovation/"},
 {outlet:"ITS Midwest", title:"2021 Project of the Year — Queue trucks with navigation alerts", date:"2021", year:2021, kind:"recognition",
  url:"https://doi.org/10.4236/jtts.2021.114035"}
];
